In [2]:
import numpy as np

In [3]:
x =np.array(((11, 12, 13), (21, 22, 23), (31, 32, 33)))

In [4]:
x.ndim

2

In [6]:
#예시를 사용함으로써 파악

import numpy as np

def test():
    """test numpy"""
    ax = np.array([1,2,3])
    ay = np.array([3,4,5])
    print(ax)
    print(ax*2)
    print(ax+10)
    print(np.sqrt(ax))
    print(np.cos(ax))
    print(ax-ay)

    # 무슨 기능을 할까?
    # 조건이 참일 경우 1번쨰 출력 아닐 경우 두 번째를
    print(np.where(ax<2, ax,10))
    print(np.cos(ax))
    # matrix 생성
    m = np.matrix([ax,ay,ax])
    print(m)
    # 역배열??
    print(m.T)

    # 다차원 배열 생성
    grid1 = np.zeros(shape=(10,10),dtype=float)
    grid2 = np.ones(shape=(10,10),dtype=float)

    print(grid1)
    print(grid2)
    print(grid1[1]+10)
    print(grid2[:,2]*2)

test()

[1 2 3]
[2 4 6]
[11 12 13]
[1.         1.41421356 1.73205081]
[ 0.54030231 -0.41614684 -0.9899925 ]
[-2 -2 -2]
[ 1 10 10]
[ 0.54030231 -0.41614684 -0.9899925 ]
[[1 2 3]
 [3 4 5]
 [1 2 3]]
[[1 3 1]
 [2 4 2]
 [3 5 3]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]


In [10]:
import numpy as np
import time

def trad_version():
    t1 = time.time()
    X = range(10000000)
    Y = range(10000000)
    z = []
    for i in range(len(X)):
        z.append(X[i]+Y[i])
    return time.time() - t1
def numpy_version():
    t1 = time.time()
    X = np.arange(10000000)
    Y = np.arange(10000000)
    z= X+Y
    return time.time() - t1

print(trad_version())
print(numpy_version())

2.00705885887146
0.04516792297363281
