# numpy
- 파이썬 list와 비슷한 형태
- 빠르고 효율적인 산술연산을 제공하는 다차원 배열 제공(ndarray 클래스)
- 반복문 없이 전체 데이터 배열 연산이 가능한 표준 수학 함수 (sum(), sqrt(), mean())

numpy.ndarray 클래스
동일한 자료형을 가지는 값들이 배열 형태로 존재함
n차원 형태로 구성이 가능하다.
각 값들은 양의 정수로 index이 부여되어 있다.

In [52]:
import numpy as np

# 1차원 배열 만들기
# numpyArray 생성
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [53]:
list2 = [[1,2,3],[4,5,6]]
arr2 =np.array(list2)

In [54]:
# 배열의 크기 확인
arr2.shape

(2, 3)

In [55]:
# 배여르이 총 개수 확인하기 -> .size
arr2.size

6

In [56]:
# 배열의 차원 확인하기 -> .ndim
arr2.ndim

2

In [57]:
# # 타입 확인
arr2.dtype

dtype('int32')

In [58]:
arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(f'배열의 크기 : {arr.shape}')
print(f'배열의 차원 : {arr.ndim}')
print(f'배열의 개수 : {arr.size}')

배열의 크기 : (2, 2, 2)
배열의 차원 : 3
배열의 개수 : 8


In [59]:
# array 연산
list1 = [1,2,3]
list2 = [4,5,6]
print(list1 + list2)
arr1 = np.array(list1)
arr2 = np.array(list2)
print(arr1 + arr2)

[1, 2, 3, 4, 5, 6]
[5 7 9]


In [60]:
# numpy 배열의 인덱싱, 슬라이싱
arr = np.array([[1,2,3],[4,5,6]])

In [61]:
# 인덱싱
# 배열명 [0][1][2]...[n]
arr[1][1]
arr[1,1]

5

In [62]:
# 슬라이싱
arr = np.array([[0,1,2,3,4,5,6,7,8,9],[0,1,2,3,4,5,6,7,8,9]])
arr[0][0:10]
arr[0,0:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
# 배열안의 모든 데이터를 0으로 초기화하여 생성하는 방법
# np.zeros(배열의 크기(튜플의 형태?))
# 2차원 배열
np.zeros((2,3))
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [64]:
# 내가 원하는 특정값으로 초기ㅗ하하면서 배열 생성하는 방법
# np.full((배열의크기),특정값)
np.full((2,3),7)

array([[7, 7, 7],
       [7, 7, 7]])

In [65]:
arr = np.array([i for i in range(1,51)])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [66]:
# numpy 자체적으로 제공하는 함수 -> 순차적으로 증가하는 넘파이 배열 생성
# arange (시작 , 끝 +1, 증감)

np.arange(1,51,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [67]:
# np.random.randint(시작,끝+1,size=(배열크기))
np.random.randint(1,100,size=(2,3,4))

array([[[71, 18, 63, 19],
        [54, 80, 69, 64],
        [78, 92, 12, 95]],

       [[79, 20, 52, 43],
        [24, 91,  2, 95],
        [89, 12, 22, 14]]])

In [68]:
### 넘파이 배열의 데이터타입 변경해보기

arr = np.ones((1,2,3))
print(arr.dtype)
print(arr)
arr1 = arr.astype(np.int64)
print(arr1.dtype)
print(arr1)

float64
[[[1. 1. 1.]
  [1. 1. 1.]]]
int64
[[[1 1 1]
  [1 1 1]]]


In [69]:
# 넘파이 배열의 데이터타입 변경해보기
# 배열의 타입을 지정하면서 배열 생성하기
arr =np.array([1.1,2.2,3],dtype = np.float64)
print(arr)
# 이미 생성되어있는 배열의 타입을 바꿔주기
arr = arr.astype('int64')
print(arr)


[1.1 2.2 3. ]
[1 2 3]


In [70]:
arr =np.arange(1,101,1)

In [71]:
# 배열과 차원을 변경해주는 reshape 함수를 사용해서 2차원 배열로 재배치
# 배열명.reshape(배열의 크기)
arr3 =arr.reshape(2,5,2,5)
print(arr3)
arr2 = np.arange(1,51).reshape(5,10)

[[[[  1   2   3   4   5]
   [  6   7   8   9  10]]

  [[ 11  12  13  14  15]
   [ 16  17  18  19  20]]

  [[ 21  22  23  24  25]
   [ 26  27  28  29  30]]

  [[ 31  32  33  34  35]
   [ 36  37  38  39  40]]

  [[ 41  42  43  44  45]
   [ 46  47  48  49  50]]]


 [[[ 51  52  53  54  55]
   [ 56  57  58  59  60]]

  [[ 61  62  63  64  65]
   [ 66  67  68  69  70]]

  [[ 71  72  73  74  75]
   [ 76  77  78  79  80]]

  [[ 81  82  83  84  85]
   [ 86  87  88  89  90]]

  [[ 91  92  93  94  95]
   [ 96  97  98  99 100]]]]


In [72]:
arr3[0,1,0,2]

13

In [73]:
arr3[0,1,1,:3]

array([16, 17, 18])

In [74]:
arr3[:,0,:,:]

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60]]])

In [75]:
arr3[:,:4,:,:]

array([[[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]],

        [[21, 22, 23, 24, 25],
         [26, 27, 28, 29, 30]],

        [[31, 32, 33, 34, 35],
         [36, 37, 38, 39, 40]]],


       [[[51, 52, 53, 54, 55],
         [56, 57, 58, 59, 60]],

        [[61, 62, 63, 64, 65],
         [66, 67, 68, 69, 70]],

        [[71, 72, 73, 74, 75],
         [76, 77, 78, 79, 80]],

        [[81, 82, 83, 84, 85],
         [86, 87, 88, 89, 90]]]])

In [76]:
arr3[0,2:4,0,2]

array([23, 33])

In [77]:
arr2[1:4,5:8]

array([[16, 17, 18],
       [26, 27, 28],
       [36, 37, 38]])

In [78]:
# 여러개의 데이터를 가져와야 하는 경우
# 배열[[행 리스트], [열 리스트]]
arr2[[2,3],[1,2]]
arr2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [79]:
arr2[[1,3,4],[4,7,9]]

array([15, 38, 50])

In [88]:
# boolean indexing
# 참과 거짓을 통해 값을 가져온다.
# how  
# 넘파이 배열 안에서 조건을 충족하는 True 인 값들만 추출하는 인덱싱 방법
# 임의의 점수 데이터 
scores = np.random.randint(50,100,(1,5))
scores


array([[58, 90, 60, 95, 87]])

In [81]:
scores >= 80

array([[ True,  True, False, False,  True]])

In [82]:
# 불리언 인덱싱
# numpy[조건]
# 인덱싱 하는 부분에 조건을 추가한다. --- true에 한해서 값을 반환한다.
scores[scores >= 80]

array([91, 93, 81])

In [89]:
name = np.array([['young','one','bo','min','jae']])


In [84]:
# name 넘파이 배열에서 특정 대상만 가져오기
name[name == 'young']

array(['young'], dtype='<U5')

In [90]:
name[scores >= 80]

array(['one', 'min', 'jae'], dtype='<U5')

## Universally Function(범용 함수)
- 넘파이에서 제공해주는 수학함수


In [95]:
# sum
# arr 라고 하는 변수에 랜덤수 1~10 범위 안에서 2행 5열 넘파이 배열
arr = np.random.randint(1,11,(2,5))
print(arr)
print(sum(arr))
print(np.sum(arr))
print(arr.sum())

[[5 5 7 9 5]
 [2 2 2 2 5]]
[ 7  7  9 11 10]
44
44


In [98]:
print(arr.mean())
print(np.mean(arr))

4.4
4.4


In [101]:
# numpy를 통한 데이터 가져오기
# text 형태의 파일을 가져오는 넘파이 
# delimiter -> 데이터가 어떤 기호를 기준으로 구분이 되었있는지 
data = np.loadtxt('height_weight(p).txt',delimiter=',')

data

array([[175.2   , 180.3   , 175.    , 169.2   , 185.2   , 188.    ,
        177.6   , 178.2   , 177.    , 179.    ],
       [144.5824, 193.952 , 174.5568, 152.7372, 121.22  , 156.9248,
        160.892 , 151.8556, 163.096 , 180.728 ]])

In [103]:
# 데이터 확인
# 데이터의 크기 확인
data.shape
# 0행 키데이터
# 1행 몸무게 데이터


(2, 10)

In [106]:
# BMI 구하는 공식  -> 몸무게(kg) / 키 (m) **2 
# 단위 변환을 진행
height = data[0] /100
print(height)

[1.752 1.803 1.75  1.692 1.852 1.88  1.776 1.782 1.77  1.79 ]


In [108]:
# 몸무게 데이터
# 파운드 -> kg 공식 ? pound / 2.204
kg = data[1] / 2.204
print(kg)

[65.6 88.  79.2 69.3 55.  71.2 73.  68.9 74.  82. ]


In [109]:
bmi= [kg / (height*height)]
print(bmi)

[array([21.37153104, 27.07018468, 25.86122449, 24.20652885, 16.03543423,
       20.14486193, 23.14392095, 21.69720651, 23.62028791, 25.59220998])]
